apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xtbdcgotx-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0254a9bb7a.hhub.p3.openshiftapps.com/rhtap/rhtap-qe:0c164988992b8354d9f7ac812e94c709c647b182@sha256:eee432e1e33c72d6e4e6ff64d5193da1ce9a243ff24a26f08d89a37d54b32562
          name: container-image
