apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xtbdcgotx-python
  janus-idp.io/tekton: xtbdcgotx-python
  backstage.io/kubernetes-id: xtbdcgotx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xtbdcgotx-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
